# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20161031_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cal_date', models.CharField(max_length=141)),
                ('cal_time', models.CharField(max_length=141)),
                ('cal_place', models.CharField(max_length=141)),
                ('cal_people', models.CharField(max_length=141)),
                ('cal_text', models.CharField(max_length=141)),
                ('cal_email', models.CharField(max_length=141)),
                ('pub_date', models.DateTimeField(verbose_name=b'date published')),
            ],
        ),
        migrations.AddField(
            model_name='squawk',
            name='squawk_date',
            field=models.CharField(default='', max_length=141),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squawk',
            name='squawk_place',
            field=models.CharField(default='', max_length=141),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squawk',
            name='squawk_time',
            field=models.CharField(default='', max_length=141),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squawk',
            name='squawk_type1',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squawk',
            name='squawk_type2',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
